name:                v4
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- HTF

ghc-options:
- -Wcompat
- -Wincomplete-uni-patterns
- -Wmissing-home-modules

library:
  source-dirs: src

tests:
  v4-test:
    main:                TestRunner.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - v4
