name:                a1
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- HTF
- random

ghc-options:
- -Wincomplete-uni-patterns
- -Wmissing-home-modules

library:
  source-dirs: src

executables:
  a1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - a1

tests:
  a1-test:
    main:                TestRunner.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - a1
